### ISSUE TITLE
Missing syntax highlighting and autocompletion

### ISSUE THREAD

**Issue by SupersonicNK** [fudgepop01/Rivals-of-Aether-GML#1]
Currently, there are a few missing functions as well as supported NTT features that aren't being highlighted by the extension.

- Template strings, denoted with back ticks. Identical to JS. Autocompleted properly, but not highlighted currently.
``` `variable: ${variable}` ```
- Function definition
```#define function_name``` OR ```#define function_name(named_args)```
- Macro (constant) definition
```#macro MACRO 1```
- The keywords `other`, `not`, `self`, and `in`
- A required argument (overshoot) during autocompletion of the easeBack functions:
```
ease_backIn(start:int, end:int, current_time:int, total_time:int, overshoot:int)
ease_backInOut(start:int, end:int, current_time:int, total_time:int, overshoot:int)
ease_backOut(start:int, end:int, current_time:int, total_time:int, overshoot:int)
```
- The following functions:
```
set_character_color_slot(shade_slot:int, r:int, g:int, b:int, ?a)
set_article_color_slot(shade_slot:int, r:int, g:int, b:int, ?a)
set_character_color_shading(shade_slot:int, shading_value)
get_color_profile_slot_r(color_slot:int, shade_slot:int)
get_color_profile_slot_g(color_slot:int, shade_slot:int)
get_color_profile_slot_b(color_slot:int, shade_slot:int)
```

**Comment by fudgepop01** [comment]
Hello! Thanks for your submission. I'll get to fixing these soon! I'm currently trying to add a basic visualizer for moves (like a diet RoABox) - so as soon as that's done (should only be another day or less) I'll add/correct these functions.
